spring.application.name=ProgettoTirocinio
server.port=9090

logging.level.it.newtech.project=DEBUG

# Abilita il database H2 in memoria
spring.datasource.url=jdbc:h2:file:./Data/comunidb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Abilita la Console H2 per vedere i dati nel browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurazioni JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Carica automaticamente gli script SQL all'avvio
# spring.sql.init.mode=always
# spring.sql.init.encoding=UTF-8 